version: '3'
services:
  app: 
    build:
      context: .
    env_file:
      - ./docker/environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes: 
      - .:/progress
      - public-data:/progress/public
      - tmp-data:/progress/tmp
      - log-data:/progress/log
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    env_file:
      - ./docker/environments/db.env
    volumes:
      - db-data:/var/lib/mysql
      
  web:
    build:
      context: docker/containers/nginx
    volumes:
      - public-data:/progress/public
      - tmp-data:/progress/tmp
    ports:
      - 8080:8080
    depends_on:
      - app
      
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: